name: docs 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material markdown-include-variants>=0.0.4 mdx-include>=1.4.2 mike griffe-typingdoc>=0.2.8 mkdocs-bootswatch>=1.1 mkdocs-glightbox>=0.4.0 mkdocs-macros-plugin>=1.3.7 mkdocs-material>=9.6.5 mkdocs-redirects>=1.2.2 mkdocstrings[python]>=0.28.1
      - run: python scripts/gendoc/dsa.py 
      - run: mkdocs gh-deploy --force